### ISSUE TITLE
com.alkacon.opencms.v8.dialogs: Method undefined

### ISSUE THREAD

**Issue by gallardo** [alkacon/modules-v8#1]
The current v8.dialogs doesn't compile "out of the box".

The "dialogs" module is not included in `all-modules.properties`, so it's not a very disruptive bug, but I'm still documenting it for future reference.

The relevant error log-trace:

```
compile-gwt:
     [echo] Deleting GWT output folder: /home/src/opencms/modules-v8/modules/com.alkacon.opencms.v8.dialogs/resources/system/modules/com.alkacon.opencms.v8.dialogs/resources/dialogs
     [java] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
     [java] [WARN] Unable to create new cache log file /home/src/opencms/modules-v8/modules/com.alkacon.opencms.v8.dialogs/resources/system/modules/com.alkacon.opencms.v8.dialogs/resources/../gwt-unitCache/gwt-unitCache-0000013CEE03FE45.
     [java] java.io.IOException: No such file or directory
     [java]     at java.io.UnixFileSystem.createFileExclusively(Native Method)
     [java]     at java.io.File.createNewFile(File.java:883)
     [java]     at com.google.gwt.dev.javac.PersistentUnitCache.createCacheFile(PersistentUnitCache.java:120)
     [java]     at com.google.gwt.dev.javac.PersistentUnitCache.<init>(PersistentUnitCache.java:264)
     [java]     at com.google.gwt.dev.javac.UnitCacheFactory.get(UnitCacheFactory.java:59)
     [java]     at com.google.gwt.dev.javac.CompilationStateBuilder.init(CompilationStateBuilder.java:403)
     [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:217)
     [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:198)
     [java]     at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
     [java]     at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
     [java]     at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
     [java]     at com.google.gwt.dev.Compiler.main(Compiler.java:177)
     [java] Compiling module com.alkacon.opencms.v8.dialogs.Dialog
     [java]    Validating units:
     [java]       [ERROR] Errors in 'file:/home/src/opencms/modules-v8/src-gwt/com/alkacon/opencms/v8/dialogs/client/ui/A_CmsDialog.java'
     [java]          [ERROR] Line 84: The method getSerializedObject(I_CmsDialogServiceAsync, String) is undefined for the type CmsRpcPrefetcher
     [java]    [ERROR] Aborting compile due to errors in some input files

BUILD FAILED
/home/src/opencms/opencms-core/modules/build.xml:199: The following error occurred while executing this line:
/home/src/opencms/opencms-core/modules/build.xml:201: The following error occurred while executing this line:
/home/src/opencms/opencms-core/modules/build-single.xml:434: Java returned: 1
```

Init info:

```
init:
     [echo] Processing dependency org.opencms.gwt of com.alkacon.opencms.v8.dialogs
     [echo] Building OpenCms Common Module com.alkacon.opencms.v8.dialogs 1.0 for OpenCms 8.5.0.9
     [echo]
     [echo] OpenCms core lib directory is: /home/src/opencms/BuildCms/build/jars-core
     [echo] OpenCms runtime lib directory is: /home/src/opencms/opencms-core/lib/runtime
     [echo] OpenCms compile lib directory is: /home/src/opencms/opencms-core/lib/compile
     [echo] OpenCms output directory is: /home/src/opencms/BuildCms
     [echo] Module input directory is: /home/src/opencms/modules-v8/modules/com.alkacon.opencms.v8.dialogs
     [echo] Module source directory is: /home/src/opencms/modules-v8/src-modules
     [echo] Detected Java version: 1.6
     [echo] Java target version: 1.5
     [echo] Tomcat home is: ${tomcat.home}
     [echo] Excluded files in Jar: **/CVS/*,**/.cvsignore,**/.nbattrs,**/.project,**/.classpath,*.gwt.xml
     [echo] Included files in Jar: **/*.properties,**/*.txt,**/*.dtd,**/*.xml,**/*.sql,**/*.gwt.rpc
     [echo]
     [echo] Module dependencies: org.opencms.gwt
     [echo] Additional lib folder: /home/src/opencms/modules-v8/modules/com.alkacon.opencms.v8.dialogs/resources/system/modules/com.alkacon.opencms.v8.dialogs/lib
     [echo] GWT module: com.alkacon.opencms.v8.dialogs.Dialog
     [echo] GWT output: /home/src/opencms/modules-v8/modules/com.alkacon.opencms.v8.dialogs/resources/system/modules/com.alkacon.opencms.v8.dialogs/resources/dialogs
     [echo] GWT source: ${module.gwt.src}

```

**Comment by tHerrmann** [comment]
Hi Alberto,

this module contains boilerplate code that is needed to build your own GWT based dialog module. It is not meant to be compiled as it is. It also won't be part of any distribution.

Greetings, Tobias

**Comment by gallardo** [comment]
Thanks. I got confused while writing some scripts and didn't know if I introduced a new bug. I checked that this module doesn't compile in the official release either, so I just needed the documented closed bug ;-) (I'm closing it)
